version: "3.9"

services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test

# phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    container_name: chatbot-phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password

  redis:
    image: redis:7.0
    container_name: chatbot-redis
    restart: unless-stopped
    tty: true
    ports:
      - '6379:6379'
    command: redis-server --requirepass root
    volumes:
      - ./cache:/var/www/cache